### ISSUE TITLE
As a Mom, I want to add a diaper entry by voice so that I can log a diaper when I change the diaper or hold my baby.

### ISSUE THREAD

**Issue by sjiang1** [COSC481W-2020Fall/GitDemo#4]
User story: 
As a Mom, I want to add a diaper entry using my voice so that I can log a diaper when I change the diaper or hold my baby.

- [ ] The app should be linked to Siri so that it can be opened by voice issue
- [ ] When the app is open, it can listen to user’s voice to add a diaper entry:
  - [x] The app will add a wet diaper entry if the user says “wet diaper” issue #5 
  - [ ] The app will add a dirty diaper entry if the user says “dirty diaper”
  - [ ] The app will automatically log the date and time for the entry
  - [ ] The app will show the logged entry for the user to double check
